name: libs

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - name: 'x86'
            abi: 'x86'
            android_abi: 'x86'
          - name: 'armeabi-v7a'
            abi: 'armeabi-v7a'
            android_abi: 'armeabi-v7a'
          - name: 'arm64-v8a'
            abi: 'arm64-v8a'
            android_abi: 'arm64-v8a'

    name: gamelibs - ${{ matrix.arch.name }}

    steps:
      - name: checkout code
        uses: actions/checkout@v6.0.3
        with:
          submodules: recursive

      - name: setting up ndk
        uses: nttld/setup-ndk@v1.5.0
        id: setup-ndk
        with:
          ndk-version: r29
          add-to-path: false

      - name: configures cmake for ${{ matrix.arch.name }}
        run: |
          cmake -G "Ninja" -B build-${{ matrix.arch.abi }} \
            -DCMAKE_TOOLCHAIN_FILE=${{ steps.setup-ndk.outputs.ndk-path }}/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=${{ matrix.arch.android_abi }} \
            -DANDROID_NDK=${{ steps.setup-ndk.outputs.ndk-path }} \
            -DANDROID_PLATFORM=android-21 \
            -DANDROID_STL=c++_static \
            -DCMAKE_BUILD_TYPE=Release \
            -DANDROID=ON \
            -DMUPENPLUSAPI=1
            src/

      - name: Compiled-gamelibs-${{ matrix.arch.name }}
        run: |
          cd build-${{ matrix.arch.abi }}
          ninja -j$(nproc)

      - name: uploading artifact ${{ matrix.arch.name }}
        if: success()
        uses: actions/upload-artifact@v7.0.1
        with:
          name: android-${{ matrix.arch.abi }}-artifacts
          path: |
            build-${{ matrix.arch.abi }}/android-${{ matrix.arch.abi }}/plugin/Release/*.so
